services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  parse-server:
    image: parseplatform/parse-server:latest
    container_name: parse-server
    env_file:
      - .env
    environment:
      - PARSE_SERVER_APPLICATION_ID=${APPLICATION_ID_LOCAL}
      - PARSE_SERVER_MASTER_KEY=${CLIENT_KEY_LOCAL}
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/dev
      - PARSE_SERVER_PORT=${PARSE_PORT}
      - PARSE_SERVER_URL=${PARSE_SERVER_URL_LOCAL}
      - PARSE_SERVER_MASTER_KEY_IPS=0.0.0.0/0
    ports:
      - "${PARSE_PORT}:${PARSE_PORT}"
    depends_on:
      - mongo

  parse-dashboard:
    image: parseplatform/parse-dashboard:latest
    container_name: parse-dashboard
    environment:
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
    volumes:
      - ./parse-dashboard-config.json:/parse-dashboard-config.json
    command: parse-dashboard --config /parse-dashboard-config.json
    ports:
      - "4040:4040"
    depends_on:
      - parse-server

volumes:
  mongo_data:
